# Generated by Django 4.1.1 on 2022-09-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_event_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredEvent',
        ),
    ]
