# Generated by Django 4.1.1 on 2022-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_registeredevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
