# Generated by Django 4.1.2 on 2022-10-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_teamleader_alter_payment_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
