# Generated by Django 4.1.2 on 2022-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_teamleader_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='otp',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='team_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
