# Generated by Django 4.1.2 on 2022-10-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_teamleader_otp_teamleader_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('full_name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnathonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('group_name', models.CharField(default=None, max_length=100)),
                ('cluster', models.IntegerField(default=0)),
                ('branch', models.CharField(default=None, max_length=100)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('is_present', models.BooleanField(default=False)),
                ('business_system', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.businesssystem')),
            ],
        ),
    ]
