# Generated by Django 4.1.2 on 2022-10-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_learnathonemployee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnathonEmployee',
            new_name='LearnathonFaculty',
        ),
    ]
