# Generated by Django 4.1.2 on 2022-10-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_learnathonemployee_learnathonfaculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnathonfaculty',
            old_name='klumainid',
            new_name='klumailid',
        ),
    ]
