# Generated by Django 4.1.2 on 2022-10-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_klumainid_learnathonfaculty_klumailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnathonfaculty',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
