# Generated by Django 4.1.2 on 2022-10-15 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_learnathonfaculty_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFSDRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review1_score', models.IntegerField(default=0)),
                ('review1_total', models.IntegerField(default=20)),
                ('review2_score', models.IntegerField(default=0)),
                ('review2_total', models.IntegerField(default=20)),
                ('review3_score', models.IntegerField(default=0)),
                ('review3_total', models.IntegerField(default=15)),
                ('review4_score', models.IntegerField(default=0)),
                ('review4_total', models.IntegerField(default=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.learnathonstudent')),
            ],
        ),
        migrations.CreateModel(
            name='MSWDRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review1_score', models.IntegerField(default=0)),
                ('review1_total', models.IntegerField(default=20)),
                ('review2_score', models.IntegerField(default=0)),
                ('review2_total', models.IntegerField(default=25)),
                ('review3_score', models.IntegerField(default=0)),
                ('review3_total', models.IntegerField(default=25)),
                ('review4_score', models.IntegerField(default=0)),
                ('review4_total', models.IntegerField(default=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.learnathonstudent')),
            ],
        ),
    ]
