# Generated by Django 4.1.2 on 2022-10-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_pfsdrubric_mswdrubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('mail_id', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
