# Generated by Django 4.1.2 on 2022-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_facultydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydata',
            name='id',
        ),
        migrations.AlterField(
            model_name='facultydata',
            name='empid',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
