# Generated by Django 4.1.2 on 2022-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_facultydata_id_alter_facultydata_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnathonstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mswdrubric',
            name='review1_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mswdrubric',
            name='review2_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mswdrubric',
            name='review3_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mswdrubric',
            name='review4_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pfsdrubric',
            name='review1_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pfsdrubric',
            name='review2_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pfsdrubric',
            name='review3_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pfsdrubric',
            name='review4_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
