# Generated by Django 4.1.2 on 2022-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_learnathonstudent_updated_at_mswdrubric_review1_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnathonstudent',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mswdrubric',
            name='review1_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mswdrubric',
            name='review2_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mswdrubric',
            name='review3_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mswdrubric',
            name='review4_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pfsdrubric',
            name='review1_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pfsdrubric',
            name='review2_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pfsdrubric',
            name='review3_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pfsdrubric',
            name='review4_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
