# Generated by Django 4.1.2 on 2022-10-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_learnathonstudent_is_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnathonstudent',
            old_name='is_present',
            new_name='is_absent',
        ),
    ]
