# Generated by Django 4.1.2 on 2022-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_is_present_learnathonstudent_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnathonstudent',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
