# Generated by Django 4.1.2 on 2022-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_learnathonstudent_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
    ]
